# Generated by Django 5.2.5 on 2025-08-22 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_vibescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('score', models.IntegerField(default=0)),
                ('game_count', models.IntegerField(default=0)),
                ('batches', models.JSONField(default=dict)),
            ],
            options={
                'unique_together': {('user_name', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='DailyVibeGameScore',
        ),
    ]
