# Generated by Django 5.2.5 on 2025-08-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygamescore',
            name='campus_name',
            field=models.CharField(default='IIT Delhi', max_length=100),
            preserve_default=False,
        ),
    ]
